// import './js/variables.js'
// import './js/primitives.js'
// import './js/toString.js'
// import './js/toNumber.js'
// import './js/toBoolean.js'
// import './js/falsyValues.js';
// import './js/math.js';
// import './js/normalization.js';
// import './js/branching.js';
// import './js/vebinar/module-1-2.js';
// import './js/homework/module-1/tasks-m1.js';
// import './js/Repeta/for.js';
// import './js/homework/module-2/my-file.js';
// import './js/homework/module-2/arrays.js';
// import './js/homework/module-2/functions.js';
// import './js/homework/module-2/tasks-m2.js';
// import './js/Repeta/functions.js';
// import './js/homework/module-3/objects.js';
// import './js/homework/module-3/module-3-1.js';
// import './js/homework/module-3/module-3-2.js';
// import './js/homework/module-3/tasks-m3.js';
// import './js/homework/module-4/callback.js';
// import './js/homework/module-4/module-4-1-callback.js';
// import './js/homework/module-4/module-4-1-closure.js';
// import './js/homework/module-4/module-4-2.js';
// import './js/homework/module-4/module-4-2-this.js';
// import './js/homework/module-4/tasks-m4.js';
// import './js/homework/module-5/constructors.js';
// import './js/homework/module-5/module-5-1.js';
// import './js/homework/module-5/module-5-2.js';
// import './js/homework/module-5/module-5-2-class-extends.js';
// import './js/homework/module-5/tasks-m5.js';
// import './js/homework/module-6/module-6-1.js';
// import './js/homework/module-6/module-6-2-tasks.js';
// import './js/homework/module-6/questions-m1-m6.js';
import './js/homework/module-6/tasks-m6.js';
